[project]
name = "diff-nca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
    "scipy>=1.15.1",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]
